### PR TITLE
Add new HD Japanese logo

### PR DESCRIPTION
**Pull request by P-Chang**
"Sui" logo is not correct but original logo has terrible alpha channel in 2017.
So, I made new logos. If you think it is ok, I commit the other chapter and "Kai" logo.

And I'm not native speaker, sorry for my crappy English.

### CODE REVIEW

**Comment by ItaloKnox** [comment]
Why did you close this? I think it looks nice.

I'll let @enumag have the final say on this.

**Comment by enumag** [comment]
Oh I kind of missed this. I'll have better a look later today but I assume there is no reason to refuse these.

**Comment by P-Chang** [comment]
Oh, it's mistake. I'm github noob.
Thank you. I'll make the Kai version.

Should I commit the chapter 2~4? 
Or it is enough for entire chapter?

**Comment by enumag** [comment]
We will probably want to include these into our graphics patch instead of here (right @ItaloKnox?) so no need to commit them anywhere.

**Comment by ItaloKnox** [comment]
Yep. Just check for me if the filenames match for all chapters and I'll update them later today after you give me the greenlight.

**Comment by enumag** [comment]
@ItaloKnox You have the greenlight. Just use [these](https://www.dropbox.com/s/rm10zndils27tno/tinified.zip?dl=0) instead - I cut them down to less than half their original size.

@P-Chang Nice work. For Kai don't bother commiting them to Meakashi, just upload them for us and we'll take care of the rest. Thank you!

**Comment by enumag** [comment]
Actually wait a sec. I think I lost some quality (although the difference is barely visible).

**Comment by enumag** [comment]
Here. These are just slightly smaller than the original ones but really lossless. https://www.dropbox.com/s/5vgyiiinpz4xzua/CG.zip?dl=0

Turns out that all the online compressors that claim to be lossless are not really lossless. So I just used my own simple script.

**Comment by enumag** [comment]
Filenames are ok except title02_j.png should actually be Title02_j.png for all chapters.

Then in oni and wata rename the english images End_1.png and End_2.png to lowercase end_1.png and end_2.png.

**Comment by P-Chang** [comment]
Sorry, wait. I find fix issue...

**Comment by ItaloKnox** [comment]
Hey @P-Chang, any news on the corrected images? I'm waiting for you. 👍

**Comment by P-Chang** [comment]
@ItaloKnox 
normaltitle svg

No filtering Image is finish barely. sorry for waiting.
And filtering needs some time...

And question for @enumag 
last logo_j.png and title02_j.png were compressed in gimp because I didn't know it needs re compress.
(other file is made in linkscape that doesn't have compressor)

True lossless file is 10 times bigger than it, which should I upload?

**Comment by P-Chang** [comment]
http://www.mediafire.com/file/cb5b1b9bw4atitd/titles.rar

Sorry for long time.
Editing and filtering and testing is finished.

**Comment by ItaloKnox** [comment]
Just checked the files and it looks good. Great work!

It's already a bit late here so I'll update the patches with them early tomorrow. Thanks a lot!

**Comment by P-Chang** [comment]
Sorry for postponement.

**Comment by enumag** [comment]
Compressed files from your last upload here: https://www.dropbox.com/s/trx2kqtxzwhpzn8/compressed.zip?dl=0

The point is that PNG compression is in fact lossless (unlike JPG compression). The difference is in decoding speed when reading the image - compressed images take longer to open. You can of course use some tool for lossy PNG compression to reduce size even more but in most cases the lossless compression is good enough.

**Comment by P-Chang** [comment]
Sure. I understand very well, thank you and sorry for rework.

**Comment by ItaloKnox** [comment]
I just pushed all the patches but [Github was acting up a bit](https://user-images.githubusercontent.com/4702556/28143608-d5fb0c54-673c-11e7-8d62-34511e88f37a.png) so I don't know if they went correctly (didn't get the green success). Extraction and file count seems fine but if someone is willing to check Tatari or Wata I would be glad. Can't see the images using the terminal, of course.

Anyway, thanks a lot @P-Chang. Your work is very appreciated.

**Comment by ItaloKnox** [comment]
I managed to check Tata and it looks fine on my home PC. Didn't see any broken images or anything, so I guess it was just zsh or github being stupid. I guess we can move on.

**Pull request closed without merging**
