### PR TITLE
Simplify ADV Mode code

### PR DESCRIPTION
**Pull request by MyLegGuy**
**Edit: This idea in the OP doesn't work. Read on for discussion.
It's up to you guys if you want to keep this pull request open for discussion of this issue, or just close it and discuss this in the actual "issues" section of Github.**

---

This is in init.txt:
```
// This variable can't be named just AdvMode as in other files because it causes an exception.
int InitAdvMode;
```

This is not true. You can call it AdvMode and access it from the other script files. The reason it isn't working right now is because you're declaring AdvMode as a new variable in every script file. Refer to the first line of this snippet.
```
int AdvMode;
AdvMode = 1;
int Line_ModeSpecific;
if (AdvMode) {
	Line_ModeSpecific = Line_Normal;
} else {
	Line_ModeSpecific = Line_WaitForInput;
}
```
If all of this code is moved to init.txt, there will be no problems. That is what I've done on my fork.
If you accept this pull request, I'll do the same for chapters 2, 3, and 4. But not chapter 5 because I haven't played it yet.

I can also make it so the font changes back to the old one if it's not in AdvMode, if that's what you want.

### CODE REVIEW

**Comment by P-Chang** [comment]
Few days ago, I tested it too.
but it didn't work in chapter end.

**Comment by ItaloKnox** [comment]
Hi, I think I could take charge of this PR but @enumag should be the one to take a look at this. Unfortunately he's out on a vacation for a couple weeks so this will take some time.

For now I'll leave it open until he comes back, I don't really want to get ahead of ourselves since we're taking a small break as well. It looks like a fair improvement and seems to work, so hopefully we'll just merge it as is as soon as possible. 👍

**Comment by MyLegGuy** [comment]
I see what you mean, P-Chang.
Loading a savefile, finishing a chapter, and then trying to go to the next one or view a TIP doesn't work. What a shame. Maybe it's due to the variable not being saved correctly.

I bet global flags are saved correctly, maybe there's an unused one that we can make use of.

But the entire point of this is so people can easily disable ADV Mode. I guess this won't be needed if you guys already have another idea.

**Comment by P-Chang** [comment]
@MyLegGuy 
Thank you for reading my broken English.

And do you know how to use global flags as strings?
I tried replace int AdvMode to globalflag, it succeed.

but I can't replace "Line_modespecific"

**Comment by MyLegGuy** [comment]
@P-Chang
To my knowledge, all global flags are integers. But this is okay because Line_ModeSpecific is an integer variable.
I also think that it is impossible to make BRAND NEW global flags. There is a hard-coded list. I've looked at the list, and there are two we can use.
The first one is called GVoiceVolume, and the second one is called GCutVoiceOnClick. Both of these are related to the unused PlayVoice function **and are completely unrelated to the voices we play using PlaySE**.

While we won't be able to completely remove the code at the top of every script file, we can make it so a very small amount of the code needs to be changed to enable and disable ADV Mode.
With my new idea, the code at the top of every script file will be changed from
```
int AdvMode;
AdvMode = 0;
int Line_ModeSpecific;
if (AdvMode) {
	Line_ModeSpecific = Line_Normal;
} else {
	Line_ModeSpecific = Line_WaitForInput;
}
```
to
```
int AdvMode;
AdvMode = GetGlobalFlag(GVoiceVolume);
int Line_ModeSpecific;
Line_ModeSpecific = GetGlobalFlag(GCutVoiceOnClick);
```
Every scenario script file would have this at the top of it. This could would not be changed depending on if ADV Mode is on or off.

Here's how init.txt would look:
```
void main()
{
	// This controls ADV Mode
	// You can also use 1 and 0 instead of TRUE and FALSE
	**SetGlobalFlag(GVoiceVolume , TRUE);**

	// This variable can't be named just AdvMode as in other files because it causes an exception.
	int InitAdvMode;
	InitAdvMode = GetGlobalFlag(GVoiceVolume);

	SetFontId(3); //0 is MS Gothic (default japanese), 1 is MS PGothic (default english), 2 is dejavu sans, 3 is source han sans chinese simplified (for chinese)
	SetCharSpacing(0); //use negative values to make characters appear closer together
	SetLineSpacing(8);
	SetFontSize(30);

	if (InitAdvMode) {
		SetNameFormat("<size=+4>{0}\n</size>");
		SetWindowPos(0, -275);
		SetWindowSize(1150, 250);
		SetWindowMargins(60, 30, 50, 30);
		// This is what Line_ModeSpecific is set to
		**SetGlobalFlag(GCutVoiceOnClick , Line_Normal);**
	} else {
		SetNameFormat("");
		SetWindowPos(0, 0);
		SetWindowSize(1240, 720);
		SetWindowMargins(60, 30, 50, 30);
		**SetGlobalFlag(GCutVoiceOnClick , Line_WaitForInput);**
	}

	SetScreenAspect("0.5625");
	SetGUIPosition(0, 0);

	CallScript( "flow" );
}
```

The only line that would be needed to be modified in the script file to switch ADV Mode on or off would be `SetGlobalFlag(GVoiceVolume , TRUE);`.

I've tested saving and it seems to work fine.

**Comment by P-Chang** [comment]
@MyLegGuy 
Wow! Nice!
I have no idea for Line_ModeSpecific is integer. lol

And

	if(GetGlobalFlag(GVoiceVolume) == 1) { OutputLineAll("", NULL, Line_ContinueAfterTyping); }
	OutputLine(NULL, "　夏を迎えても、朝の空気は切るように冷たい。",
		   NULL, "Even though we were approaching summer, the morning air still had a frigid bite.", GetGlobalFlag(GCutVoiceOnClick););
	if(GetGlobalFlag(GVoiceVolume) == 1) { ClearMessage(); } else { OutputLineAll(NULL, "\n", Line_ContinueAfterTyping); }
	
is works fine.

It is fix for

https://github.com/07th-mod/meakashi/issues/13

It is not big problem until chapter4 but chapter5 and probably 6 7 8 have big problem with it.
It is related in same reason, after loading savegame, if game uses "callscript" game will lost variable.

but it needs replace few else to if.

BGI to MG compiler or Antlr3.Runtime really dislike

	if (GetGlobalFlag(GVoiceVolume) == 1) {
		OutputLineAll("", NULL, Line_ContinueAfterTyping);
		OutputLine(NULL, "　激しい戦いは、豊富な運動量と肘によるブロックで序盤、沙都子が優位に立つかに見えたが、箸さばきの致命的な差が形勢を一気にひっくり返す！",
			   NULL, "<size=-2>It was a tough battle. Blocking with her full momentum and an elbow in the opening moves, Satoko appeared to have the upper hand. But the difference in our proficiency with chopsticks proved to be fatal and gave me the upper hand!</size>", GetGlobalFlag(GCutVoiceOnClick););
	} else {
		OutputLine(NULL, "　激しい戦いは、豊富な運動量と肘によるブロックで序盤、沙都子が優位に立つかに見えたが、箸さばきの致命的な差が形勢を一気にひっくり返す！",
			   NULL, "It was a tough battle. Blocking with her full momentum and an elbow in the opening moves, Satoko appeared to have the upper hand. But the difference in our proficiency with chopsticks proved to be fatal and gave me the upper hand!", GetGlobalFlag(GCutVoiceOnClick););
	}
	if (GetGlobalFlag(GVoiceVolume) == 1) { ClearMessage(); } else { OutputLineAll(NULL, "\n", Line_ContinueAfterTyping); }


And two question.

Doesn't GVoiceVolume conflict with your voice mod?
I found it yesterday, it is awesome.

And can't we use GlobalFlags from GVChie to GVOther ?

**Comment by MyLegGuy** [comment]
@P-Chang 
First off, I have never played chapter 5, Meakashi. I'm still having fun making theories and stuff with chapters 1 through 4. So a lot of those is assumptions made by looking at chapter 5's source code, what you've told me, and the issue you linked. Please correct me if I say something incorrect.

I made this list to organize what I know about the scope of variables:
1. Global flags can be accessed from anywhere and are saved when the application closes.
1. Variables made within script files can be accessed from any other script file.
1. You cannot make a new variable with the same name as one you have already made in the **same script** file.
	* For example, I can't make two variables named AdvMode in the same script file. I can, however, make another variable named AdvMode in the next script file.
1. If you loaded a save file that was in the middle of a script file, all variables created within script files will **only be usable until the script file finishes**.
	* This explains the loading problem with my first idea, the one to just put AdvMode in init.txt.
1. The CallScript command is weird. When used, rules 4 AND 3 apply. If you loaded a save file that was in the middle of the script, all the variables will be gone. If you didn't load a save file, then you can't declare a new variable with the same name in the loaded script file.

I really hope I'm missing something here, because this is the dumbest variable scope system ever.

**Looking at the issue you linked and what you said, there should be a huge problem with Meakashi right now. If you load a save file that's in the middle of a script file that then uses CallScript, AdvMode won't be accessible anymore, causing the called script to crash**
Is this correct?

If this is correct, I can only think of two solutions.
First solution:
	* Just as you did in the code you wrote in your message, just use GetGlobalFlag instead of AdvMode. This is probably not the solution we want because the code is less neat.
Second solution:
	* Make a different name for the AdvMode variable. This can apply to every script, or just ones that are called using CallScript. I think this is the best solution. It's impossible to know if we can declare AdvMode as a new variable in every script, because it depends on if the user loaded a save file. With this method, it doesn't matter because we'll always be declaring a variable that's unique to that script file. We could call the variable AdvMode_filename where "filename" is the name of the file that this AdvMode variable is used in. An example would be AdvMode_meak_01 for the AdvMode variable for meak_01.txt.

The code you said the compiler doesn't like may work if you put it on multiple lines.
Here's an example "if" statement from hima_tips_09:
```
if(GetGlobalFlag(GLanguage) == 1)
{
}
else
{
}
```

Using GCutVoiceOnClick and GVoiceVolume WILL interfere with the PlayVoice command. This isn't a problem in chapters 1 through 4, because the PlayVoice command doesn't even work.
However, fear not! Chapter 1, Onikakushi, is the only chapter we need to use the voice global flags because every chapter after chapter 1 has more unused global flags.

For every chapter, **except Onikakushi**, you can use the global flags LOnikakushiDay and GOnikakushiDay. They are leftovers that the lazy developers didn't remove.

We can't use GVChie and GVOther. These global flags **do not exist** in Higurashi: When They Cry. This is the reason the PlayVoice command doesn't work in chapters 1 through 4. It tries to look for those global flags, can't find them, and then freezes. Chapter 5 is the first one to fix this problem by just removing those checks.

---
...You know, that issue you linked was filled with spoilers. I haven't even played the game yet. ;(

**Comment by P-Chang** [comment]
@MyLegGuy 
At first, sorry for spoilers. but don't worry.
There are many missing links that I can't understand after watching chapter 8.
I think you didn't play chapter5 is you didn't play it in new version, sorry...


I find the reason is why compiler dislike my code, i use semicolon double time...


Probably you didn't miss anything. game lost the variables after loading savegame.
But strange, loading savegame after selecting chapter. everything is fine...
Maybe loading can't throw away variable and saving can't save variable...what?

Or, we didn't use variable correctry. I think you use decompiler.

In BGICompiler.Compiler/BGIValue/BGIValue(ITree)

There are different name type variable,
"TYPEINT" "TYPESTRING" "TYPEBOOL" etc

Maybe It will save and load correctry, but I can't understand how to use it.
Or it is same as we already used.


You are right. however we can saving after freezing and it can be loaded correctly after selecting chapter.

Fortunetly, Alomost of callscript are the end of script in chapter5.
But I think chapter 6 may be hellish.

My code is bit dirty but it uses only 2 flags and replace is easy in my opinion.
although I'm really noob, I might find problem with that.

Using 2 or 3 variable for same issue is  hard for debug.

And it passed my hellish callscript stress test.

Actually playvoice doesn't work without editing dll, but you said "easily" so I edited dll.
I want to leave it if it is possible.


I see, there is GV** flag in chapter 1 but these are deleted after chapter2. I understand.

**Comment by MyLegGuy** [comment]
I accept your apology as there's no way you could've known I hadn't played chapter 5 yet.

Oh, I never actually looked at chapter 1. I saw those flags weren't in chapter 3, so I just assumed they weren't in chapter 1 either. There's no reason we can't use the GV*** flags if we want to, they'll probably work.

I don't really have any new information or ideas because I have no more time to investigate before I go on vacation tomorrow. See you in 10 days or so.

**Comment by P-Chang** [comment]
My idea didn't work in NVL mode...
Completely sorry.

**Comment by enumag** [comment]
This was actually my first implementation when I started with ADV Mode. It didn't work with save & load so I had to drop it - which you found out too. The comments after that are long and difficult to read. Did you guys come up with anything you want me to be aware of?

**Comment by MyLegGuy** [comment]
Not anything that you don't know about now.
We discussed using global flags in place of the AdvMode variable and the PlayVoice command.
You've probably read about those in #90 though.

**Pull request closed without merging**
